# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com
project_name: epusdt
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    flags:
      - -trimpath
    ldflags:
      - -s -w
      - -X github.com/assimon/luuu/config.AppVersion={{ .Version }}
archives:
  - id: epusdt
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format: zip
    files:
      - .env.example
      - static/*
checksum:
  disable: true
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  disable: true
